BuenoOffice/Controllers/About/AboutController.cs
using System.Web.Mvc;

namespace BuenoOffice.Controllers.About
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

BuenoOffice/Controllers/Car/CarController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BuenoOffice.DependecyInjection;
using BuenoOffice.Mapping;
using BuenoOffice.Service.DTOs.Car;
using BuenoOffice.Service.Services.Car.Interface;
using BuenoOffice.ViewModels.Car;
using Microsoft.Practices.Unity;

namespace BuenoOffice.Controllers.Car
{
    public class CarController : Controller
    {
        private readonly IUnityContainer container;

        public CarController()
        {
            container = ContainerConfiguration.Container;
        }

        [Authorize]
        public ActionResult Index()
        {
            var carService = container.Resolve<ICarService>();
            var mapper = ServiceMapper.ConfigureMapper();

            var myCarsViewModel = new MyCarsViewModel();
            myCarsViewModel.NewCar = new CreateCarViewModel();
            InitializeDropDown(myCarsViewModel, null, null);

            var email = System.Web.HttpContext.Current.User.Identity.Name;
            var cars = carService.GetUserCarsByUserMail(email);
            myCarsViewModel.Cars = cars != null && !cars.Count.Equals(0) ? mapper.Map<List<CarViewModel>>(cars) : new List<CarViewModel>();

            return View(myCarsViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCar(MyCarsViewModel carsInfo)
        {
            var carService = container.Resolve<ICarService>();
            var mapper = ServiceMapper.ConfigureMapper();
            const string index = "Index";

            InitializeDropDown(carsInfo, carsInfo.NewCar.SelectBrandId, carsInfo.NewCar.SelectModelId);
            var email = System.Web.HttpContext.Current.User.Identity.Name;

            if (ModelState.IsValid)
            {
                var newCar = mapper.Map<NewCarDto>(carsInfo.NewCar);
                carService.CreateCar(newCar, email);
                ViewBag.Status = true;
                return RedirectToAction(index);
            }

            var cars = carService.GetUserCarsByUserMail(email);
            carsInfo.Cars = cars != null && !cars.Count.Equals(0) ? mapper.Map<List<CarViewModel>>(cars) : new List<CarViewModel>();

            return View(index, carsInfo);
        }

        [HttpPost]
        public JsonResult GetAllModelsByBrand(int brandId)
        {
            var carService = container.Resolve<ICarService>();
            var models = carService.GetAllModelsByBrand(brandId);

            if (models == null || !models.Any())
            {
                return Json(new { success = false, responseText = $"Any model was found for this brand id = {brandId}"}, JsonRequestBehavior.AllowGet);
            }
            
            var result = new List<object>();
            foreach (var model in models)
            {
                result.Add(new { model.Text, model.Value, model.Selected });
            }

            return Json(new { success = true, data = result }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetAllVersionsByModel(int modelId)
        {
            var carService = container.Resolve<ICarService>();
            var versions = carService.GetAllVersionsByModel(modelId);

            if (versions == null || !versions.Any())
            {
                return Json(new { success = false, responseText = $"Any version was found for this model id = {modelId}" }, JsonRequestBehavior.AllowGet);
            }

            var result = new List<object>();
            foreach (var version in versions)
            {
                result.Add(new { version.Text, version.Value, version.Selected });
            }

            return Json(new { success = true, data = result }, JsonRequestBehavior.AllowGet);
        }

        #region Private Methods

        private void InitializeDropDown (MyCarsViewModel myCars, int? brandId, int? modelId)
        {
            var carService = container.Resolve<ICarService>();

            myCars.NewCar.Brands = carService.GetAllBrands();
            myCars.NewCar.Models = brandId != null ? carService.GetAllModelsByBrand(brandId.Value) : new List<SelectListItem>();
            myCars.NewCar.Versions = modelId != null ? carService.GetAllVersionsByModel(modelId.Value) : new List<SelectListItem>();
            myCars.NewCar.Conversions = carService.GetAllConversions();
            myCars.NewCar.Colors = carService.GetAllColors();
        }

        #endregion
    }
}

BuenoOffice/Controllers/Contact/ContactController.cs
using System.Web.Mvc;
using BuenoOffice.DependecyInjection;
using BuenoOffice.Mapping;
using BuenoOffice.Service.DTOs.Contact;
using BuenoOffice.Service.Services.Contact.Interface;
using BuenoOffice.ViewModels.Contact;
using Microsoft.Practices.Unity;

namespace BuenoOffice.Controllers.Contact
{
    public class ContactController : Controller
    {
        private readonly IUnityContainer container;

        public ContactController()
        {
            container = ContainerConfiguration.Container;
        }

        public ActionResult Index()
        {
            var message = TempData["SendMessageSucess"]?.ToString();
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.Status = true;
                ViewBag.Message = message;
            }
            return View();
        }

        [HttpPost]
        public ActionResult SendMessage(ContactMessageViewModel contactMessage)
        {
            const string indexContact = "Index";
            var contactService = container.Resolve<IContactService>();
            var mapper = ServiceMapper.ConfigureMapper();

            if (ModelState.IsValid)
            {
                var contactMessageDto = mapper.Map<ContactMessageDto>(contactMessage);
                contactService.SendMessage(contactMessageDto);

                TempData["SendMessageSucess"] = "Mensagem enviada com sucesso.";
                return RedirectToAction(indexContact);
            }

            ViewBag.Status = false;
            ViewBag.Message = "Preencha os campos obrigatórios corretamente.";
            return View(indexContact, contactMessage);
        }

        [HttpPost]
        public JsonResult IsValidEmail(string email)
        {
            var contactService = container.Resolve<IContactService>();
            var isValid = contactService.IsValidEmail(email);
            return Json(new { success = isValid }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult IsValidPhone(string phone)
        {
            var contactService = container.Resolve<IContactService>();
            var isValid = contactService.IsValidPhone(phone);
            return Json(new { success = isValid }, JsonRequestBehavior.AllowGet);
        }
    }
}

BuenoOffice/Controllers/Faq/FaqController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using BuenoOffice.DependecyInjection;
using BuenoOffice.Infrastructure.Utilities.Enums.Faq;
using BuenoOffice.Mapping;
using BuenoOffice.Service.DTOs.Faq;
using BuenoOffice.Service.Services.Faq.Interface;
using BuenoOffice.ViewModels.Faq;
using Microsoft.Practices.Unity;

namespace BuenoOffice.Controllers.Faq
{
    public class FaqController : Controller
    {
        private readonly IUnityContainer container;

        public FaqController()
        {
            container = ContainerConfiguration.Container;
        }

        public ActionResult Index()
        {
            var faqService = container.Resolve<IFaqService>();
            var mapper = ServiceMapper.ConfigureMapper();

            var faqDtos = faqService.LastQuestions();
            var faqViewModel = new FaqViewModel();
            faqViewModel.Answers = mapper.Map<List<FaqAnswerViewModel>>(faqDtos);

            return View(faqViewModel);
        }

        [Authorize]
        public ActionResult FaqManager()
        {
            var faqService = container.Resolve<IFaqService>();

            var faqManagerViewModel = new FaqManagerViewModel();
            faqManagerViewModel.FaqStatus = faqService.GetAllFaqStatus();
            faqManagerViewModel.Search = string.Empty;
            faqManagerViewModel.PageNumber = 1;
            faqManagerViewModel.PageSize = 10;

            return View(faqManagerViewModel);
        }

        [HttpPost]
        public ActionResult SearchQuestion(string search)
        {
            const string indexFaq = "Index";
            var faqService = container.Resolve<IFaqService>();
            var mapper = ServiceMapper.ConfigureMapper();

            if (!string.IsNullOrEmpty(search))
            {
                var faqDtos = faqService.SearchQuestions(search);
                var faqViewModel = new FaqViewModel();
                faqViewModel.Answers = mapper.Map<List<FaqAnswerViewModel>>(faqDtos);

                return View(indexFaq, faqViewModel);
            }

            return RedirectToAction(indexFaq);
        }

        [HttpPost]
        public ActionResult SendQuestion(string question)
        {
            const string indexFaq = "Index";
            var faqService = container.Resolve<IFaqService>();

            if (!string.IsNullOrEmpty(question))
            {
                var faqDto = new FaqDto { Question = question };
                faqService.CreateOrUpdate(faqDto);
            }

            return RedirectToAction(indexFaq);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchFaqByQuestionAndStatusAndPage(FaqManagerViewModel faqManager)
        {
            const string manager = "FaqManager";

            if (ModelState.IsValid)
            {
                var faqService = container.Resolve<IFaqService>();
                var mapper = ServiceMapper.ConfigureMapper();
                var previousSearch = faqManager.Search;
                var previousFaqStatusId = faqManager.SelectFaqStatusId;

                var pagedList = faqService.GetPagedFaqByQuestionAndStatus(faqManager.Search, (FaqStatus)faqManager.SelectFaqStatusId, faqManager.PageNumber, faqManager.PageSize);
                faqManager = mapper.Map<FaqManagerViewModel>(pagedList);
                faqManager.Search = previousSearch;
                faqManager.SelectFaqStatusId = previousFaqStatusId;
                faqManager.FaqStatus = faqService.GetAllFaqStatus();

                return View(manager, faqManager);
            }

            return View(manager, faqManager);
        }

        [Authorize]
        public ActionResult GetFaqManagerByPage(string search, int faqStatusId, int pageNumber, int pageSize)
        {
            var viewModel = new FaqManagerViewModel
            {
                Search = search,
                SelectFaqStatusId = faqStatusId,
                PageSize = pageSize,
                PageNumber = pageNumber
            };

            return SearchFaqByQuestionAndStatusAndPage(viewModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult FaqManagerDetails(int faqId)
        {
            const string faqManagerModal = "FaqManagerModal";
            var faqService = container.Resolve<IFaqService>();
            var mapper = ServiceMapper.ConfigureMapper();

            var faqDto = faqService.GetFaqById(faqId);
            var faq = mapper.Map<FaqAnswerViewModel>(faqDto);
            return PartialView(faqManagerModal, faq);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CompleteFaq(FaqAnswerViewModel faq)
        {
            const string faqManager = "FaqManager";

            if (ModelState.IsValid)
            {
                var faqService = container.Resolve<IFaqService>();
                var mapper = ServiceMapper.ConfigureMapper();

                var faqDto = mapper.Map<FaqDto>(faq);
                faqDto.AnswerDate = DateTime.Now;
                faqService.CreateOrUpdate(faqDto);

                return RedirectToAction(faqManager);
            }

            return RedirectToAction(faqManager);
        }

        [Authorize]
        [HttpPost]
        public ActionResult DisableFaq(int faqId, string search, int faqStatusId, int pageNumber, int pageSize)
        {
            const string getFaqManagerByPage = "GetFaqManagerByPage";
            var faqService = container.Resolve<IFaqService>();

            faqService.DisableFaq(faqId);

            return RedirectToAction(getFaqManagerByPage, new { search, faqStatusId, pageNumber, pageSize });
        }
    }
}

BuenoOffice/Views/Shared/_BaseModal.cshtml
<div id="myModal" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="myModalContent"></div>
        </div>
    </div>
</div>  

BuenoOffice/Views/Shared/_Layout.cshtml
@using System.Web.Script.Serialization
@{
    var serializer = new JavaScriptSerializer();
    var identity = ((System.Security.Principal.GenericPrincipal)User).Identity;
    var formsIdentity = identity as FormsIdentity;
    var userRole = "Cliente";
    if (formsIdentity != null && formsIdentity.Ticket != null && !string.IsNullOrEmpty(formsIdentity.Ticket.UserData))
    {
        userRole = serializer.DeserializeObject(formsIdentity.Ticket.UserData).ToString();
    }

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Bueno Office System" />
    <meta name="author" content="Sérgio Bueno" />

    <title>@ViewBag.Title - Mecânica Bueno</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/animate.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/prettyPhoto.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/responsive.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/jquery.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.prettyPhoto.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.isotope.min.js" type="text/javascript"></script>
    <script src="~/Scripts/main.js" type="text/javascript"></script>
    <script src="~/Scripts/wow.min.js" type="text/javascript"></script>
</head>
<body>

    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div class="top-number"><p><i class="fa fa-thumbs-up"></i> Fique por dentro! </p></div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div class="social">
                            <ul class="social-share">
                                <li><a href="https://www.facebook.com/sergio.dacostabueno"><i class="fa fa-facebook"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <img class="bueno-office-logo" src="~/Images/Layout/logo-oficial.png" alt="logo">
                </div>

                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Página Inicial", "Index", "Home")</li>
                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Orçamento", "Index", "Home")</li>
                            <li>@Html.ActionLink("Serviços", "Index", "Home")</li>
                        }
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">Outros <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                @if (userRole.Equals("Administrador"))
                                {
                                    <li>@Html.ActionLink("Gerenciar FAQ", "FaqManager", "Faq")</li>
                                    <li>@Html.ActionLink("Cadastrar Funcionário", "Employee", "User")</li>
                                    <li>@Html.ActionLink("Gerenciar Funcionários", "EmployeeManagement", "User")</li>
                                }
                                else
                                {
                                    <li>@Html.ActionLink("FAQ", "Index", "Faq")</li>
                                }
                                <li>@Html.ActionLink("Contato", "Index", "Contact")</li>
                                <li>@Html.ActionLink("Sobre", "Index", "About")</li>
                            </ul>
                        </li>
                        @if (!Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Criar conta", "Registration", "User")</li>
                        }
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">Minha conta <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                @if (Request.IsAuthenticated)
                                {
                                    <li>@Html.ActionLink("Meus carros", "Index", "Car")</li>
                                    <li><a href="#">Orçamentos</a></li>
                                    <li><a href="#">Serviços</a></li>
                                    <li>@Html.ActionLink("Alterar perfil", "EditUser", "User")</li>
                                    <li>@Html.ActionLink("Alterar senha", "ResetPassword", "User")</li>
                                    <li>@Html.ActionLink("Sair", "Logout", "User", null, new { style = "background-color: red;" })</li>
                                }
                                else
                                {
                                    <li>@Html.ActionLink("Acessar", "Index", "User", null, new { style = "background-color: green;" })</li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @RenderBody()

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2017. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li>@Html.ActionLink("Página Inicial", "Index", "Home")</li>
                        <li>@Html.ActionLink("Sobre", "Index", "About")</li>
                        <li>@Html.ActionLink("Faq", "Index", "Faq")</li>
                        <li>@Html.ActionLink("Contato", "Index", "Contact")</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

BuenoOffice/Views/Shared/_NewCar.cshtml
@model BuenoOffice.ViewModels.Car.MyCarsViewModel
    
<script src="~/Scripts/car.js" type="text/javascript"></script>

<section id="contact-page">
    <div class="container">
        <br />
        <br />
        <div class="center">
            <h2>Cadastre um novo carro a sua conta!</h2>
            <p class="lead">Preencha as informações abaixo para vincular um novo veiculo a sua conta.</p>
        </div>
        <div class="row contact-wrap">
            <div class="alert alert-success" style="display: none"></div>
            @using (Html.BeginForm("CreateCar", "Car", FormMethod.Post, new { @class = "contact-form", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="col-sm-5 col-sm-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.SelectBrandId, new { id = "brandLabel" })
                        @Html.DropDownListFor(m => m.NewCar.SelectBrandId, Model.NewCar.Brands, "Escolha a marca...", new { @class = "form-control", id = "brandDropDown" })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.SelectBrandId)
                        </p>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.SelectModelId, new { id = "modelLabel" })
                        @Html.DropDownListFor(m => m.NewCar.SelectModelId, Model.NewCar.Models, "Escolha o modelo...", new { @class = "form-control", id = "modelDropDown" })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.SelectModelId)
                        </p>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.SelectVersionId, new { id = "versionLabel" })
                        @Html.DropDownListFor(m => m.NewCar.SelectVersionId, Model.NewCar.Versions, "Escolha a versão...", new { @class = "form-control", id = "versionDropDown" })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.SelectVersionId)
                        </p>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.SelectColorId, new { id = "colorLabel" })
                        @Html.DropDownListFor(m => m.NewCar.SelectColorId, Model.NewCar.Colors, "Escolha a cor...", new { @class = "form-control", id = "colorDropDown" })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.SelectColorId)
                        </p>
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.SelectConversionId, new { id = "conversionLabel" })
                        @Html.DropDownListFor(m => m.NewCar.SelectConversionId, Model.NewCar.Conversions, "Escolha o câmbio...", new { @class = "form-control", id = "conversionDropDown" })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.SelectConversionId)
                        </p>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.ManufactureYear, new {id = "manufactureYearLabel" })
                        @Html.EditorFor(m => m.NewCar.ManufactureYear, new {htmlAttributes = new {@class = "form-control", id = "manufactureYearNumber" } })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.ManufactureYear)
                        </p>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.ModelYear, new { id = "modelYearLabel" })
                        @Html.EditorFor(m => m.NewCar.ModelYear, new { htmlAttributes = new { @class = "form-control", id = "modelYearNumber" } })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.ModelYear)
                        </p>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.NewCar.Mileage, new { id = "mileageLabel" })
                        @Html.EditorFor(m => m.NewCar.Mileage, new { htmlAttributes = new { @class = "form-control", id = "mileageNumber" } })
                        <p class="alert-error">
                            @Html.ValidationMessageFor(m => m.NewCar.Mileage)
                        </p>
                    </div>
                    <div>
                        <button type="submit" name="submit" class="btn btn-primary btn-lg">Cadastrar</button>
                    </div>
                </div>
            }
        </div>
    </div>
</section>